### ISSUE TITLE
Redmine 4.1.0-8 error

### ISSUE THREAD

**Issue by konpega** [5inf/redmine_filelinks#2]
Hello,
First of all this is great which I am searching for months at the beginnig of 2020, when I saw I was very happy.
But after copying and restarting, I can't even login.
Error code as below.
AH01114: HTTP: failed to make connection to backend: 127.0.0.1, referer: http://127.0.0.1:81/custom_fields?tab=IssueCustomField

Any idea.

**Comment by konpega** [comment]
Hi

I saw an expression which is adressing custom_table. That plugin link is as follows. 
https://www.redmine.org/plugins/custom-tables

After this illıumination :) and while I couldn't login to my system, I reinstalled the program. This time I did not install custom table and check this plugin. Yes, I can login and it is seen in the plugin list.
Also I think I need help about using because I create a custom area and copy that link to that cell. I applied the procedure for chrome. Link seems really as a link but it is trying to reach a folder over a new chrome tab and it fails.

What is wrong and is there any possibility to solve inconsistency with Custom_Table plugin.

Thanks in advance

**Comment by 5inf** [comment]
I'm currently not seeing any direct relation between anything this plugin does and a failure to load the the Redmine custom fields page at the link you provided above (/custom_fields?tab=IssueCustomField).

I am also, from a first quick glance at the source code of the custom tables plugin, seeing no relation to why the combination of both plugins should fail.

Which version of Redmine are you running?

Are you sure your problem is related to this plugin or the interaction of this plugin with the custom-tables plugin?
Are there other plugins installed?
What does the Redmine server log say?

**Comment by konpega** [comment]
Sorry while I reinstall the program I don't have chance. But when I did not install the custom table I can login and see the name of the plugin in the plugins. 
At this moment how can we activate or use this opportunity? Can we add any alink at any point?

I am using RedminePlusAgile 4.1.0-8. Below list contains the stable/running version.

Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.5.7-p206 (2019-10-01) [x64-mingw32]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.25.0
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.12
  redmine_checklists             3.1.18
  redmine_contacts               4.3.2
  redmine_filelinks              0.0.0
  redmine_issues_tree            0.0.14
  redmine_monitoring_controlling 0.1.1
  redmine_people                 1.6.0
  redmine_products               2.1.2
  redmine_smile_togglesidebar    1.0.7

Normally in server we have as follows

Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.5.7-p206 (2019-10-01) [x64-mingw32]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.25.0
  Filesystem                     
Redmine plugins:
  custom_tables                  1.0.6
  redmine_agile                  1.5.3
  redmine_checklists             3.1.16
  redmine_contacts               4.3.0
  redmine_issues_tree            0.0.14
  redmine_monitoring_controlling 0.1.1
  redmine_people                 1.5.1
  redmine_products               2.1.2
  redmine_reporter               1.0.3
  redmine_smile_togglesidebar    1.0.7

**Comment by konpega** [comment]
![image](https://user-images.githubusercontent.com/61666724/103533956-b0034f80-4e96-11eb-8b1b-072ec6052fe9.png)

![image](https://user-images.githubusercontent.com/61666724/103534041-d1fcd200-4e96-11eb-8ac5-44096e2d2ebb.png)

But somehow it is working even this warning. But I couldn't understand how we use this plugin, how affect the links. Could you explain a little bit detail?

**Comment by konpega** [comment]
Hi collaques

Is there any body who can see the difference with this plugin? Is it working? Is there any settings?

**Comment by 5inf** [comment]
The warning in the comment screenshot above "key :title is duplicated" is fixed in 22b7414.
This had however nothing to do with causing another plugin to fail.

This plugin has no settings. Its only purpose is to provide a macro which can be used to properly support formatting links to files on (mostly) Windows shares which are written into Wiki pages or other text fields that support Markup in Redmine.
Examples on how to use the macro are given the Readme.

I am closing this issue as there is no problem I can reproduce.
